//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblEğitimler
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Bu Alanı Boş Geçemezsiniz!")]
        public string Başlık { get; set; }
        public string AltBaşlık1 { get; set; }
        public string AltBaşlık2 { get; set; }

        [StringLength(10, ErrorMessage ="Lütfen en fazla 10 karakter giriniz.")]
        public string GNO { get; set; }
        public string Tarih { get; set; }
    }
}
